# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b142cb345a04f660b08343728a566701f365594e308dbfeb0af8540e40c9a1c5ddb6b53ba824999e1b68204c69902c24e92179cd1f44274086c637af2b85b6

test:
  secret_key_base: d14436fd1b049bddfbb7594336b30dabf6f0cb5d979ec6364dc77fef53d5e736fa4c0fb029992778f3b0475ec84613d6bac9e66535d8fe9a8f830deb716a48a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
